spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:develop}
  application:
    name: tech-challenge-api
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/tech_challenge}
  main:
    allow-bean-definition-overriding: true
server:
  port: ${APP_PORT:8081}
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    defaults:
      enabled: true
    mongo:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus,metrics-requiredMetricName,metrics,health-path,health,info

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

---
spring:
  config:
    activate:
      on-profile: develop
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/tech_challenge}

logging:
  level:
    com.fiap.itmoura.tech_challenge: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://admin:admin123@mongodb:27017/tech_challenge?authSource=admin}

logging:
  level:
    com.fiap.itmoura.tech_challenge: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.repository.query: DEBUG

